name: Tests unitaire Python
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Installer python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    
    - name: Installer les d√©pendances
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
    
    - name: Installer pytest
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html
    
    - name: Faire le test et la documentation
      run: |
        pytest test.py
      env:
        CI: true
